{
  "openapi": "3.0.0",
  "info": {
    "title": "KeyVaultClient",
    "version": "7.6",
    "description": "The key vault client performs cryptographic key operations and vault operations against the Key Vault service.",
    "x-typespec-generated": [
      {
        "emitter": "@azure-tools/typespec-autorest"
      }
    ]
  },
  "security": [
    {
      "OAuth2Auth": ["https://vault.azure.net/.default"]
    }
  ],
  "tags": [],
  "paths": {},
  "servers": [
    {
      "url": "{vaultBaseUrl}",
      "variables": {
        "vaultBaseUrl": {
          "format": "uri",
          "x-ms-skip-url-encoding": true,
          "default": "none"
        }
      }
    }
  ],
  "components": {
    "examples": {
      "GetDeletedSecrets": {
        "value": {
          "value": [
            {
              "recoveryId": "https://myvault.vault.azure.net/deletedsecrets/listdeletedsecrettest0",
              "deletedDate": 1493937855,
              "scheduledPurgeDate": 1501713855,
              "contentType": "plainText",
              "id": "https://myvault.vault.azure.net/secrets/listdeletedsecrettest0",
              "attributes": {
                "enabled": true,
                "created": 1493937855,
                "updated": 1493937855,
                "recoveryLevel": "Recoverable+Purgeable"
              }
            }
          ],
          "nextLink": "https://myvault.vault.azure.net:443/deletedsecrets?api-version=7.2&$skiptoken=eyJOZXh0TWFya2VyIjoiMiExNDQhTURBd01EWXlJWE5sWTNKbGRDOU1TVk5VUkVWTVJWUkZSRk5GUTFKRlZGUkZVMVF3THpZMU16ZERSRVJGTlRJNU5qUkRSa1pDTVRkQ1JVWXhORGszUXpSQ1JEZEVJVEF3TURBeU9DRXlNREUzTFRBMUxUQTBWREl5T2pRME9qUXdMamsxTnpZeE1UbGFJUS0tIiwiVGFyZ2V0TG9jYXRpb24iOjB9&maxresults=1"
        }
      },
      "GetDeletedSecret": {
        "value": {
          "recoveryId": "https://myvault.vault.azure.net/deletedsecrets/GetDeletedSecretTest",
          "deletedDate": 1493938433,
          "scheduledPurgeDate": 1501714433,
          "id": "https://myvault.vault.azure.net/secrets/GetDeletedSecretTest/b595353d9c39413d80626575b3b5d865",
          "attributes": {
            "enabled": true,
            "created": 1493938433,
            "updated": 1493938433,
            "recoveryLevel": "Recoverable+Purgeable"
          }
        }
      },
      "RecoverDeletedSecret": {
        "value": {
          "id": "https://myvault.vault.azure.net/secrets/SecretCreateDeleteRecoverPurgeTest/16f5f7feb7004280b7f3b8ac50cd01f9",
          "attributes": {
            "enabled": true,
            "created": 1493937960,
            "updated": 1493937960,
            "recoveryLevel": "Recoverable+Purgeable"
          }
        }
      },
      "GetSecrets": {
        "value": {
          "value": [
            {
              "contentType": "plainText",
              "id": "https://myvault.vault.azure.net/secrets/listsecrettest0",
              "attributes": {
                "enabled": true,
                "created": 1482189047,
                "updated": 1482189047
              }
            }
          ],
          "nextLink": "https://myvault.vault.azure.net:443/secrets?api-version=7.2&$skiptoken=eyJOZXh0TWFya2VyIjoiMiE4OCFNREF3TURJeUlYTmxZM0psZEM5TVNWTlVVMFZEVWtWVVZFVlRWREVoTURBd01ESTRJVEl3TVRZdE1USXRNVGxVTWpNNk1UQTZORFV1T0RneE9ERXhNRm9oIiwiVGFyZ2V0TG9jYXRpb24iOjB9&maxresults=1"
        }
      },
      "SetSecret": {
        "value": {
          "value": "mysecretvalue",
          "id": "https://myvault.vault.azure.net/secrets/crpsecret/03bcccc7c8cf4546a0e3e21e52560441",
          "attributes": {
            "enabled": true,
            "created": 1493938459,
            "updated": 1493938459,
            "recoveryLevel": "Recoverable+Purgeable"
          }
        }
      },
      "DeleteSecret": {
        "value": {
          "recoveryId": "https://myvault.vault.azure.net/deletedsecrets/GetDeletedSecretTest",
          "deletedDate": 1493938433,
          "scheduledPurgeDate": 1501714433,
          "id": "https://myvault.vault.azure.net/secrets/GetDeletedSecretTest/b595353d9c39413d80626575b3b5d865",
          "attributes": {
            "enabled": true,
            "created": 1493938433,
            "updated": 1493938433,
            "recoveryLevel": "Recoverable+Purgeable"
          }
        }
      },
      "GetSecret": {
        "value": {
          "value": "mysecretvalue",
          "id": "https://myvault.vault.azure.net/secrets/mysecretname/4387e9f3d6e14c459867679a90fd0f79",
          "attributes": {
            "enabled": true,
            "created": 1493938410,
            "updated": 1493938410,
            "recoveryLevel": "Recoverable+Purgeable"
          }
        }
      },
      "UpdateSecret": {
        "value": {
          "id": "https://myvault.vault.azure.net/secrets/crpsecret/03bcccc7c8cf4546a0e3e21e52560441",
          "contentType": "myContentType",
          "attributes": {
            "enabled": true,
            "created": 1493938459,
            "updated": 1493938459,
            "recoveryLevel": "Recoverable+Purgeable"
          },
          "tags": {
            "mytag": "myvalue"
          }
        }
      },
      "BackupSecret": {
        "value": {
          "value": "KUF6dXJlS2V5VmF1bHRTZWNyZXRCYWNrdXBWMS5taWNyb3NvZnQuY29tZXlKcmFXUWlPaUppTlRjMk5ESTVaaTB5TlRZNExUUTFZbVV0WW1aaFlTMHpOMlZrTURkbVl6QmpPREVpTENKaGJHY2lPaUpTVTBFdFQwRkZVQ0lzSW1WdVl5STZJa0V4TWpoRFFrTXRTRk15TlRZaWZRLmhERDdfVW9aU1ptR2JYN1dYUTU5WDkxZ0FQb05kdDcwZE1BbmgzbjQ3eWNjbkRNOU5vTm1hY0NHZmlNeUwxU0FlZDk0UjhBNDAtVE81TDNfQ05Qal9pdWIyaW03Z21nbHNPNnFFUVVIWU1tOEh2Wl9odFRrdEl4QzRPWEowYTB0S2hscnczZlBvVVFDZHVGcFg0ekEzYTR4VTZXTUNfYjZZVXZqUjZnSGM5TFRUR2tIazh1RTY0aVQ4cmt5RDRrU3RNcXhnU2lfRVZwUUdjWGdfNE9wQ1dBOUFha0N1NkpybGRaQW9BLUtXTWpQbGhaWHFYWGMyVkJlbUJjRTQ1YzY3QWhqYjJrSi1uQ1c5dHBjWS1JZ3JEUHFzWkswOS1WbHVtcl9SbzQzcG5FeW5jVFpTdzZlX1h6VnN0dUFOZHdiM0E2OVR1c1hfYkJKZ0J2SGQ4cDJSUS5WMTlhMVRacjZ2UjJHdEVaWGtOOXJRLmhwMU5IMmwtZklWbVgwWlNfTlRzekJfUEs1aktDUU5rSnJyRUhRQmZjQ2VjdHhmVU5uVlB6MVBqRWNDblZuV0pCUk4zTlFKZm01MjFLRHp1MzBIVUFEUGVmVHJyMFVFS2x5QTM2cThoWFY3VTdoQ0dHNk85NVpYclRsZlVENDI5RTNTNTQxdVBmWGpGR2cxbHlucFNTNnAtVkFzaXFlY1lpQWNuM1hhNzRhUm5xS3N3ZzhyU1ZOX09hSVU3ak1VVUhYZWY1ZmN0NlFrdWFfYkt6Z2dtR2ZiT2RTdVdNRmVQaF9mMkJMUFNGN3k1NThEMFZxSVlNY0JJR0dMU3BQUU93Q094OFF3Y3NVUEp4ZDFuWkVYYjRVNEJZYlhBcmFMX0NwekYxZlhYWVBsdmVUSGdKNVdrR28tWXNJVzAtT3ZqVGdLN2hIamxpR1psd29HOVUtbTJSVDZfbkhseHhVRFMyY3JseGNmay1OOTlXd0tEdUxFMTM5ZE1mN2RCSEl1aTdxd0RXdm1TN2JMTHYzM05Wd19XSl9DT1VGQjgycy1ELXk0UEdIRzVackhsSDgxa25mLVpRblU0SmZfY2lhMWhmWlY3ZFMxb21UZDQtNnJwZmpTMGxFT3VfZTQ5bUpYUGFpZ0hyLWFQYkFzTXJJQ2JvOUVIR2IzMXJ5SlR2QXF2ZmJDbU10bkdLUDV6aUNiZFh3SU5ONzBJTk5lZnJLWGZkZFBUd0RSV3d1ZkxCcGNlU0U0SG5EWVZVQmdkMDl4UUZidG12UDhhTXhhUlpGSTNpWG1fbmpCNmZfdlNhZUNUakdVYVVuRE1QQkdOQWQ5T2xVX3dvUnMtalNCVnVqd1FQSGlGcm5RWElkXzBRdXRYSm54cTU4aUtlTGJvNDJtOHgwaXBRcnB4aEZoUDdHNmZOWXAwVmxXR0RxZ1Q0VlpPQkZsZWRKUU0yaDQtb2xTbXdtUms0M0Y1cjdKd3h4aENqU1JReWx1MGEyQ0ZONWMyZjIxTElZaFliLWNReWFXMDNpV3hsb04zWld5cDJIb1FlUmZPR3lXUzBiU2NBT3JndGpBYnJaUFIwMGRRNnpSOHNBczFYUzh3dzBlaVczbFpsdjJwVWFxOVpTeVhnTS14b2NTOS1ueXRaWGtWWlUwX2dDVXJBV0ZKNG5XdW9oTGM1RkkyRWFQNWR0SXVWa3dnbXlsR1gtYk9ZeHp3dzVGYmI1V3VEbnJ5aDBMSnVic3Q4VXdLdnl3bk1jQ3duMjZSVTNxQVRudGJubVhJS0FyeGkwMldQVk9oTXdpUWZuX2h1TWk5emp3MEVuaXNWdktNWUNnR2xqNWlGZW5Tc0FKUXBiLUY4bng3OWFJQlJaTUc1a0huUDR5dGxmNm9FTkRsRXNJY21aeEtOdEIzcmJPdVROYUhLTXZBNmxSNzlMMDJZSTZrcEdrUUZnaHpIaTBjTWkwbFdCejRTM1AzUEMzZElZSVlQZ0Q2S05kT2FLWHkta0dWdUlsWFNmVlVrMnpzM0NBeTJhZEJjV0NMV094ZkRoQnlwNTl4MHpBRExvdnZySHRLOWF6TGN3N0lTbVl6eUhYMkpobVdReUYtTFd1VzhfcW41SkFVYlB5Z0RTRDYyMi1PTGZQVDZmc2VTWUVBUTFLVWRwZTFnSV9hZWxVT3FaRWN1aE5SckU1YUp0LTN5TEVLVWZIWXF6WTlGbHJrUE5MUC03Y2xRbmEySEhfZmMzZV9LTGtGUDFhQTJjM0RVaERseGhsTzB2bFVmV0c5eXpXaDNZN0NmRFlFMlBaUzZBcFBlYy0wa1NDcEVKMmtCcnFzWG4yeDJDX0FDdTdCTTVGZXNJQkN0M2NqSEdQSVVQRnEteGVmT0RCXzBQcXZDTXpBOHg5Zm10Ny1sNHhVQlJaa0dtZExhZFoxVzdFUXRNRVpsSWMtbDF1V1UzTU15cFZpVWR0OWxJUHVQVUEwc1NrbWxrTGhNSjgyNE5QN0hyVi01dC1ZNDcxaWVKMHdEUjFxMmU4MU8yazdNeTFlTDY3TlY4OVBHYU81SVR5WG1ueUVXMGtVbl9qa3l1UVRkV3dsS09HZVZIYkJWNFpxSXZHWjdQUS02TEE5eXc3a0dyZFRhVFZXOEdOOV9GY1c2VUhjbzA0U3dqTzY2S2x4VlFJWWpBdEZPZlBjWW5xNzF1RndyQS1UZHVDZG1sUFBHOVpjc2tiQmdrbF8wVk90dmhuc0pwYXZKZ2Zka0d3OF9qMkQzd0Jzemd0VndHNk9nNW16eVFwM2pFc0w3UmNtcXd6WFBOaDdKYXdHVDBJMlRvZHYyQ1Z3MDkzWjJlODFXR1NxRnlIejAxdjFBaGN2T2VWdmFjUGM2Y1JJaVduNW93ZF80d2FBdjlyNjVVdmtWa1FLRXpHUmo5eTZILXdZTTMyV1JyMzBlOU9MRTNKUU5POV9kNjRTRmIwSjZHa2VxUmtnNkVXc2xqN1JYLVU1VlhrS1BtMzNpS3c5dGU2NVBqQUNnZThRVDBYVWZEaUx5a1pGeUdpZ09ZMS1TVDFxUlE1eUhMTXhEc3BPRjFXd1lMQ2c2b3hocTlWMm55Z0U1cUJ2ZnYyWUtFaDdjM1dWNjJrYkw3UXJ2d0xkMHVRZ1FwYmUza3E3dGJzcC1lNWlud3cyY0YxQzByeHNScGZJRHlJMmg4b2xHMi1RQUZkWmtlMUlmaE1FZmNfdUdXX2pqSGJSWXVzYnZCRnpKMDdaOVJsVnFMR1A2WXBnTDFsRTFOY09xUVJyYVdxckdDTWZ6SzZMVENQSl93aHJRam9WTzdVRDJIUEVnUjZ2S3U3cWlmTmo3UjE5OUJuRi1EZmlnbk1TYTFKZkZadDNuVXVZOEhMUXRoUzN4MUMxOE50d3dsaDVuNGxYS3d5MERHenljbVNweE05QkdPNTFRckFmSXRfY0xHbUlzMlJ4MzMyeDRIdEZ3Z05nRzFBazNIUno4TlJ4V3lhNWhjb1NoYURXekhES2gyOVp3Vm4wYXVzeWJpal9uNlFGcnZZbjRSOHdPNlRQV3FrS09JcHkxc1lQNWxyNDc1anZSRVZGaFdCWDBiUXdJdnNlM0Q0a0dFQzgzU3FWYkhxY3phZTNwOFNxaG5tQW5ZYzBIbWp4clJfZUMzT0hYVFBGUFZmNDlVWHdrQjIwY1lvcjJ1dzBaTzJ2TUg3S1QwcjBSWDBQVy1qcGpORFpjSGRSNVVCMXFacGlWLWxaYkw0eF9IZW14aWUxY0RPOHNQSXhIOElUSWtOV0tTR1N2eWdraHBBbGl2RzVEZXJObElkeFE2c0tHQ3RtMDEyT2xjN2thaVFaNHh0TjR5ZVpPU2xyS0s0OTlIcWhObzhkNTNsbFFfMW5ncWlHbzhUSDlzWkFrclYwclc3dkJOSF92UlhBdTc2MnlpZGhZUURYYXJXSEFUMm9DU2hEN1lOdnotekoyZGtEajJMcW5CdFNCWFh5T2xsM3o0ZWFITDd2MDZ1QTgxMVBKQU5YZUdoenNaNFVQQUQ2Q0E4cGlxSHB4WGkxODRHNEJETVU4S2VHeHZLWnJiUlNOT2pTOFNrQUJKZERfSklIZ1RhNEFhNzdPUmNZcVY3OWZ5djFZVHNma2lLR2NUYzZIUjZzUVpsamt2U0NQNjdtTTRGUHRqTHlfX1pDQlNwdnRSVWd5UlpNM1dSOUViNHkxa29uRG4zUjMzN2lpSzdfbGtIa1UtZ21VbUpZUVdnUjYzT01pZUdRUHdNR3BSZXlRWE5yckJVTDN2Z2JYdjlac1ZDcDh1NHRwQjBleXJvUXgxZC1KSWJvOWVyR1VlX0ZzU1Fpd0tIaGFIUk02Nzh5dENkcHJFbDBWeG92TFVrX0xNcTFjN1R4MG5jbFl2WE4yUjhEMXNhU2FibkJSd19CU2tZMFNMSXdhb2RpY2o2ZzdLd0ZfMXB2eThhNF9LbnJNLUNkenBvdHA0aTd4QUJuY2JRVUEwWkpsYlp1elRpR0F4ZjFnclk1Z0dZOTVoWi1XZG1lOWlSazBHRTJGN3d4MlJyLUVvS3lZRjNjak0xMWt6MWFmME9fNFdyOXJoU3JrX1NHU3l2a3ZCTW9NZ0xOX0tSS1BlTjlqUnpwRlVST2VnN2NCbGlhdy1odnZhY2lCeDN2UWRqTE5jTldQdU1UbzVmME1QbmU4TUtXcFBoWjBySElMaEVuYW1pcG82X3pzNjczcE9ma09FS0JWWE9mUDEzR0UwS25SWTBab2JPLWRub254LVdBY1dodFZvX08xbkwwTWE5ZXFMMURhRGhJU0JNbVRIM1hkY2dDTnF0emIwcVMtS1l5Mk9zRzZOakRDVEM1aEI3MXIwU09WMUprNFV2QjdYemxTTW9YUXJnTzF2ZFVwSGtxaVhUM1RJZmlQMWRKcDEweDlSMlp5R0lzUzljQUtNMEZyMGRxQmJmQy16NTJpcWZweW4zUVVqb1Fld2hPYnJwUEZGOF9lUmVNRlIwSXZjUkxnMHpwek56UzU1N1pkQkZhemxNTThLcnkwN2QyUDAyTnZtclUtN1ZjOW8wZm1qem9WOHVVTG9PMkJHdmFRdnFJNmtBTmQ5VWo1X2JkY2NVUzBhcklzcGFZa1UtUXQtNnQxYU5YUUdGZEtUbFMwSVowek54bkNIZWRySEE4SkYtOFg3d1ZpRW1McXJQbU1Sd25sbWx3SnhxLVlReWMydmdUallSbUxCVU5TS3VrZkJsa2VnMmlCRWdySksxVlNyRWswX0ZvOXkzV1EwVlZuNXhEZXlGc1JuWDI4Tkl6alFQLVNXaHhYbzdPYm5YY1cxZHlWNE1fYjdzM096cEMwOTJWcGZYQkpaTDhBeHgxNGY2TmJzTEpXLW95VEdsaTJFb2FCZHJKQ2JkQlNOdWJlbGdRRmU2V2hqSjRGdlNrYVJISjFTT3ltbGFtQmYwaVNDOGM2X1g2SkZORjNmOXYuQjc5SDJvbVIyTU52SndydHVzclJ4UQ"
        }
      },
      "GetSecretVersions": {
        "value": {
          "value": [
            {
              "id": "https://myvault.vault.azure.net/secrets/listsecretversionstest/11a536561da34d6b8b452d880df58f3a",
              "attributes": {
                "enabled": true,
                "created": 1481851699,
                "updated": 1481851699
              }
            }
          ],
          "nextLink": "https://myvault.vault.azure.net:443/secrets/listsecretversionstest/versions?api-version=7.2&$skiptoken=eyJOZXh0TWFya2VyIjoiMiExNDQhTURBd01EWXlJWE5sWTNKbGRDOU1TVk5VVTBWRFVrVlVWa1ZTVTBsUFRsTlVSVk5VTHpGRU5EazJNa0l4UlVRM09EUkVRa1k0T1RsR016TXpNa1UwTnpZNFFqY3dJVEF3TURBeU9DRTVPVGs1TFRFeUxUTXhWREl6T2pVNU9qVTVMams1T1RrNU9UbGFJUS0tIiwiVGFyZ2V0TG9jYXRpb24iOjB9&maxresults=1"
        }
      },
      "RestoreSecret": {
        "value": {
          "contentType": "text",
          "id": "https://myvault.vault.azure.net/secrets/SecretBackupRestoreTest/01ddd6e3a0d34d35bb5bccecb1251837",
          "attributes": {
            "enabled": true,
            "nbf": 1262332800,
            "exp": 1893484800,
            "created": 1493938113,
            "updated": 1493938113,
            "recoveryLevel": "Recoverable+Purgeable"
          }
        }
      }
    },
    "parameters": {
      "Azure.Core.Foundations.ApiVersionParameter": {
        "name": "api-version",
        "in": "query",
        "description": "The API version to use for this operation.",
        "required": true,
        "x-ms-parameter-location": "method",
        "x-ms-client-name": "apiVersion",
        "schema": {
          "type": "string",
          "minLength": 1
        },
        "examples": {
          "GetDeletedSecrets": {
            "value": "7.6"
          },
          "GetDeletedSecret": {
            "value": "7.6"
          },
          "PurgeDeletedSecret": {
            "value": "7.6"
          },
          "RecoverDeletedSecret": {
            "value": "7.6"
          },
          "GetSecrets": {
            "value": "7.6"
          },
          "SetSecret": {
            "value": "7.6"
          },
          "DeleteSecret": {
            "value": "7.6"
          },
          "GetSecret": {
            "value": "7.6"
          },
          "UpdateSecret": {
            "value": "7.6"
          },
          "BackupSecret": {
            "value": "7.6"
          },
          "GetSecretVersions": {
            "value": "7.6"
          },
          "RestoreSecret": {
            "value": "7.6"
          }
        }
      }
    },
    "securitySchemes": {
      "OAuth2Auth": {
        "type": "oauth2",
        "flows": {
          "implicit": {
            "authorizationUrl": "https://login.microsoftonline.com/common/oauth2/authorize",
            "scopes": {
              "https://vault.azure.net/.default": ""
            }
          }
        }
      }
    },
    "schemas": {
      "Attributes": {
        "type": "object",
        "description": "The object attributes managed by the KeyVault service.",
        "properties": {
          "enabled": {
            "type": "boolean",
            "description": "Determines whether the object is enabled."
          },
          "nbf": {
            "type": "integer",
            "format": "unixtime",
            "description": "Not before date in UTC.",
            "x-ms-client-name": "NotBefore"
          },
          "exp": {
            "type": "integer",
            "format": "unixtime",
            "description": "Expiry date in UTC.",
            "x-ms-client-name": "Expires"
          },
          "created": {
            "type": "integer",
            "format": "unixtime",
            "description": "Creation time in UTC.",
            "readOnly": true
          },
          "updated": {
            "type": "integer",
            "format": "unixtime",
            "description": "Last updated time in UTC.",
            "readOnly": true
          }
        }
      },
      "BackupSecretResult": {
        "type": "object",
        "description": "The backup secret result, containing the backup blob.",
        "properties": {
          "value": {
            "type": "string",
            "format": "base64url",
            "description": "The backup blob containing the backed up secret.",
            "readOnly": true
          }
        }
      },
      "DeletedSecretBundle": {
        "type": "object",
        "description": "A Deleted Secret consisting of its previous id, attributes and its tags, as well as information on when it will be purged.",
        "properties": {
          "value": {
            "type": "string",
            "description": "The secret value."
          },
          "id": {
            "type": "string",
            "description": "The secret id."
          },
          "contentType": {
            "type": "string",
            "description": "The content type of the secret."
          },
          "attributes": {
            "$ref": "#/components/schemas/SecretAttributes"
          },
          "tags": {
            "type": "object",
            "description": "Application specific metadata in the form of key-value pairs.",
            "additionalProperties": {
              "type": "string"
            }
          },
          "kid": {
            "type": "string",
            "description": "If this is a secret backing a KV certificate, then this field specifies the corresponding key backing the KV certificate.",
            "readOnly": true
          },
          "managed": {
            "type": "boolean",
            "description": "True if the secret's lifetime is managed by key vault. If this is a secret backing a certificate, then managed will be true.",
            "readOnly": true
          },
          "recoveryId": {
            "type": "string",
            "description": "The url of the recovery object, used to identify and recover the deleted secret."
          },
          "scheduledPurgeDate": {
            "type": "integer",
            "format": "unixtime",
            "description": "The time when the secret is scheduled to be purged, in UTC",
            "readOnly": true
          },
          "deletedDate": {
            "type": "integer",
            "format": "unixtime",
            "description": "The time when the secret was deleted, in UTC",
            "readOnly": true
          }
        }
      },
      "DeletedSecretItem": {
        "type": "object",
        "description": "The deleted secret item containing metadata about the deleted secret.",
        "properties": {
          "id": {
            "type": "string",
            "description": "Secret identifier."
          },
          "attributes": {
            "$ref": "#/components/schemas/SecretAttributes"
          },
          "tags": {
            "type": "object",
            "description": "Application specific metadata in the form of key-value pairs.",
            "additionalProperties": {
              "type": "string"
            }
          },
          "contentType": {
            "type": "string",
            "description": "Type of the secret value such as a password."
          },
          "managed": {
            "type": "boolean",
            "description": "True if the secret's lifetime is managed by key vault. If this is a key backing a certificate, then managed will be true.",
            "readOnly": true
          },
          "recoveryId": {
            "type": "string",
            "description": "The url of the recovery object, used to identify and recover the deleted secret."
          },
          "scheduledPurgeDate": {
            "type": "integer",
            "format": "unixtime",
            "description": "The time when the secret is scheduled to be purged, in UTC",
            "readOnly": true
          },
          "deletedDate": {
            "type": "integer",
            "format": "unixtime",
            "description": "The time when the secret was deleted, in UTC",
            "readOnly": true
          }
        }
      },
      "DeletedSecretListResult": {
        "type": "object",
        "description": "The deleted secret list result",
        "properties": {
          "value": {
            "type": "array",
            "description": "A response message containing a list of deleted secrets in the key vault along with a link to the next page of deleted secrets.",
            "items": {
              "$ref": "#/components/schemas/DeletedSecretItem"
            },
            "readOnly": true
          },
          "nextLink": {
            "type": "string",
            "description": "The URL to get the next set of deleted secrets.",
            "readOnly": true
          }
        }
      },
      "DeletionRecoveryLevel": {
        "type": "string",
        "description": "Reflects the deletion recovery level currently in effect for secrets in the current vault. If it contains 'Purgeable', the secret can be permanently deleted by a privileged user; otherwise, only the system can purge the secret, at the end of the retention interval.",
        "enum": [
          "Purgeable",
          "Recoverable+Purgeable",
          "Recoverable",
          "Recoverable+ProtectedSubscription",
          "CustomizedRecoverable+Purgeable",
          "CustomizedRecoverable",
          "CustomizedRecoverable+ProtectedSubscription"
        ],
        "x-ms-enum": {
          "name": "DeletionRecoveryLevel",
          "modelAsString": true,
          "values": [
            {
              "name": "Purgeable",
              "value": "Purgeable",
              "description": "Denotes a vault state in which deletion is an irreversible operation, without the possibility for recovery. This level corresponds to no protection being available against a Delete operation; the data is irretrievably lost upon accepting a Delete operation at the entity level or higher (vault, resource group, subscription etc.)"
            },
            {
              "name": "RecoverablePurgeable",
              "value": "Recoverable+Purgeable",
              "description": "Denotes a vault state in which deletion is recoverable, and which also permits immediate and permanent deletion (i.e. purge). This level guarantees the recoverability of the deleted entity during the retention interval (90 days), unless a Purge operation is requested, or the subscription is cancelled. System wil permanently delete it after 90 days, if not recovered"
            },
            {
              "name": "Recoverable",
              "value": "Recoverable",
              "description": "Denotes a vault state in which deletion is recoverable without the possibility for immediate and permanent deletion (i.e. purge). This level guarantees the recoverability of the deleted entity during the retention interval (90 days) and while the subscription is still available. System wil permanently delete it after 90 days, if not recovered"
            },
            {
              "name": "RecoverableProtectedSubscription",
              "value": "Recoverable+ProtectedSubscription",
              "description": "Denotes a vault and subscription state in which deletion is recoverable within retention interval (90 days), immediate and permanent deletion (i.e. purge) is not permitted, and in which the subscription itself  cannot be permanently canceled. System wil permanently delete it after 90 days, if not recovered"
            },
            {
              "name": "CustomizedRecoverablePurgeable",
              "value": "CustomizedRecoverable+Purgeable",
              "description": "Denotes a vault state in which deletion is recoverable, and which also permits immediate and permanent deletion (i.e. purge when 7 <= SoftDeleteRetentionInDays < 90). This level guarantees the recoverability of the deleted entity during the retention interval, unless a Purge operation is requested, or the subscription is cancelled."
            },
            {
              "name": "CustomizedRecoverable",
              "value": "CustomizedRecoverable",
              "description": "Denotes a vault state in which deletion is recoverable without the possibility for immediate and permanent deletion (i.e. purge when 7 <= SoftDeleteRetentionInDays < 90).This level guarantees the recoverability of the deleted entity during the retention interval and while the subscription is still available."
            },
            {
              "name": "CustomizedRecoverableProtectedSubscription",
              "value": "CustomizedRecoverable+ProtectedSubscription",
              "description": "Denotes a vault and subscription state in which deletion is recoverable, immediate and permanent deletion (i.e. purge) is not permitted, and in which the subscription itself cannot be permanently canceled when 7 <= SoftDeleteRetentionInDays < 90. This level guarantees the recoverability of the deleted entity during the retention interval, and also reflects the fact that the subscription itself cannot be cancelled."
            }
          ]
        }
      },
      "Error": {
        "type": "object",
        "properties": {
          "code": {
            "type": "string",
            "description": "The error code.",
            "readOnly": true
          },
          "message": {
            "type": "string",
            "description": "The error message.",
            "readOnly": true
          },
          "innererror": {
            "$ref": "#/components/schemas/Error"
          }
        },
        "nullable": true
      },
      "KeyVaultError": {
        "type": "object",
        "description": "The key vault error exception.",
        "properties": {
          "error": {
            "$ref": "#/components/schemas/Error"
          }
        }
      },
      "SecretAttributes": {
        "type": "object",
        "description": "The secret management attributes.",
        "properties": {
          "enabled": {
            "type": "boolean",
            "description": "Determines whether the object is enabled."
          },
          "nbf": {
            "type": "integer",
            "format": "unixtime",
            "description": "Not before date in UTC.",
            "x-ms-client-name": "NotBefore"
          },
          "exp": {
            "type": "integer",
            "format": "unixtime",
            "description": "Expiry date in UTC.",
            "x-ms-client-name": "Expires"
          },
          "created": {
            "type": "integer",
            "format": "unixtime",
            "description": "Creation time in UTC.",
            "readOnly": true
          },
          "updated": {
            "type": "integer",
            "format": "unixtime",
            "description": "Last updated time in UTC.",
            "readOnly": true
          },
          "recoverableDays": {
            "type": "integer",
            "format": "int32",
            "description": "softDelete data retention days. Value should be >=7 and <=90 when softDelete enabled, otherwise 0.",
            "readOnly": true
          },
          "recoveryLevel": {
            "$ref": "#/components/schemas/DeletionRecoveryLevel"
          }
        }
      },
      "SecretBundle": {
        "type": "object",
        "description": "A secret consisting of a value, id and its attributes.",
        "properties": {
          "value": {
            "type": "string",
            "description": "The secret value."
          },
          "id": {
            "type": "string",
            "description": "The secret id."
          },
          "contentType": {
            "type": "string",
            "description": "The content type of the secret."
          },
          "attributes": {
            "$ref": "#/components/schemas/SecretAttributes"
          },
          "tags": {
            "type": "object",
            "description": "Application specific metadata in the form of key-value pairs.",
            "additionalProperties": {
              "type": "string"
            }
          },
          "kid": {
            "type": "string",
            "description": "If this is a secret backing a KV certificate, then this field specifies the corresponding key backing the KV certificate.",
            "readOnly": true
          },
          "managed": {
            "type": "boolean",
            "description": "True if the secret's lifetime is managed by key vault. If this is a secret backing a certificate, then managed will be true.",
            "readOnly": true
          }
        }
      },
      "SecretItem": {
        "type": "object",
        "description": "The secret item containing secret metadata.",
        "properties": {
          "id": {
            "type": "string",
            "description": "Secret identifier."
          },
          "attributes": {
            "$ref": "#/components/schemas/SecretAttributes"
          },
          "tags": {
            "type": "object",
            "description": "Application specific metadata in the form of key-value pairs.",
            "additionalProperties": {
              "type": "string"
            }
          },
          "contentType": {
            "type": "string",
            "description": "Type of the secret value such as a password."
          },
          "managed": {
            "type": "boolean",
            "description": "True if the secret's lifetime is managed by key vault. If this is a key backing a certificate, then managed will be true.",
            "readOnly": true
          }
        }
      },
      "SecretListResult": {
        "type": "object",
        "description": "The secret list result.",
        "properties": {
          "value": {
            "type": "array",
            "description": "A response message containing a list of secrets in the key vault along with a link to the next page of secrets.",
            "items": {
              "$ref": "#/components/schemas/SecretItem"
            },
            "readOnly": true
          },
          "nextLink": {
            "type": "string",
            "description": "The URL to get the next set of secrets.",
            "readOnly": true
          }
        }
      },
      "SecretProperties": {
        "type": "object",
        "description": "Properties of the key backing a certificate.",
        "properties": {
          "contentType": {
            "type": "string",
            "description": "The media type (MIME type)."
          }
        }
      },
      "SecretRestoreParameters": {
        "type": "object",
        "description": "The secret restore parameters.",
        "properties": {
          "value": {
            "type": "string",
            "format": "base64url",
            "description": "The backup blob associated with a secret bundle.",
            "x-ms-client-name": "secretBundleBackup"
          }
        },
        "required": ["value"]
      },
      "SecretSetParameters": {
        "type": "object",
        "description": "The secret set parameters.",
        "properties": {
          "value": {
            "type": "string",
            "description": "The value of the secret."
          },
          "tags": {
            "type": "object",
            "description": "Application specific metadata in the form of key-value pairs.",
            "additionalProperties": {
              "type": "string"
            }
          },
          "contentType": {
            "type": "string",
            "description": "Type of the secret value such as a password."
          },
          "attributes": {
            "$ref": "#/components/schemas/SecretAttributes"
          }
        },
        "required": ["value"]
      },
      "SecretUpdateParameters": {
        "type": "object",
        "description": "The secret update parameters.",
        "properties": {
          "contentType": {
            "type": "string",
            "description": "Type of the secret value such as a password."
          },
          "attributes": {
            "$ref": "#/components/schemas/SecretAttributes"
          },
          "tags": {
            "type": "object",
            "description": "Application specific metadata in the form of key-value pairs.",
            "additionalProperties": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}
